apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  selector:
    app: jenkins
  type: NodePort
  ports:
  - nodePort: 31011
    port: 8080
    targetPort: 8080
    protocol: TCP

---
# JNLP(JAVA NETWORK LAUNCH PROTOCOL) is used to Connect 
# to/launch your java application( here Jenkins) from a remote location
apiVersion: v1
kind: Service
metadata:
  name: jenkins-jnlp
spec:
  type: ClusterIP
  ports:
    - port: 50000
      targetPort: 50000
  selector:
    app: jenkins